# Generated by Django 3.2.6 on 2021-09-28 19:56

from django.db import migrations, models
import tree.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bursary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residence',
            options={'ordering': ('path',)},
        ),
        migrations.AddField(
            model_name='residence',
            name='unit',
            field=models.CharField(choices=[('county', 'County'), ('subc', 'Sub County'), ('ward', 'Ward'), ('cvu', 'County Village Unit'), ('subl', 'Sub location')], default=('county', 'County'), max_length=150),
        ),
        migrations.AlterField(
            model_name='residence',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of administrative area'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='path',
            field=tree.fields.PathField(order_by=('unit', 'name')),
        ),
    ]
