# Generated by Django 3.2.6 on 2021-09-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary_app', '0002_alter_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_applicant',
            field=models.BooleanField(default=False, help_text='Designates this user as an applicant. Once true this status should not be changed. ', verbose_name='applicant'),
        ),
    ]
